In [ ]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

fight_stats = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\ufc_fight_details.csv")
fight_stats.head(5)

,fight_url,event_name,event_url,fighter_f1,fighter_f2,fighter_f1_url,fighter_f2_url,outcome_f1,outcome_f2,nickname_f1,nickname_f2,bout_type,is_title_bout,perf_bonus,method,round,time,time_format,referee,details,totals_perround_round_1_fighter_f1,totals_perround_round_1_fighter_f2,totals_perround_round_1_fighter_f1_url,totals_perround_round_1_fighter_f2_url,totals_perround_round_1_kd_f1,totals_perround_round_1_kd_f2,totals_perround_round_1_sig_str_f1,totals_perround_round_1_sig_str_f2,totals_perround_round_1_total_str_f1,totals_perround_round_1_total_str_f2,totals_perround_round_1_td_f1,totals_perround_round_1_td_f2,totals_perround_round_1_sub_att_f1,totals_perround_round_1_sub_att_f2,totals_perround_round_1_rev_f1,totals_perround_round_1_rev_f2,totals_perround_round_1_ctrl_f1,totals_perround_round_1_ctrl_f2,totals_perround_round_2_fighter_f1,totals_perround_round_2_fighter_f2,totals_perround_round_2_fighter_f1_url,totals_perround_round_2_fighter_f2_url,totals_perround_round_2_kd_f1,totals_perround_round_2_kd_f2,totals_perround_round_2_sig_str_f1,totals_perround_round_2_sig_str_f2,totals_perround_round_2_total_str_f1,totals_perround_round_2_total_str_f2,totals_perround_round_2_td_f1,totals_perround_round_2_td_f2,totals_perround_round_2_sub_att_f1,totals_perround_round_2_sub_att_f2,totals_perround_round_2_rev_f1,totals_perround_round_2_rev_f2,totals_perround_round_2_ctrl_f1,totals_perround_round_2_ctrl_f2,totals_perround_round_3_fighter_f1,totals_perround_round_3_fighter_f2,totals_perround_round_3_fighter_f1_url,totals_perround_round_3_fighter_f2_url,totals_perround_round_3_kd_f1,totals_perround_round_3_kd_f2,totals_perround_round_3_sig_str_f1,totals_perround_round_3_sig_str_f2,totals_perround_round_3_total_str_f1,totals_perround_round_3_total_str_f2,totals_perround_round_3_td_f1,totals_perround_round_3_td_f2,totals_perround_round_3_sub_att_f1,totals_perround_round_3_sub_att_f2,totals_perround_round_3_rev_f1,totals_perround_round_3_rev_f2,totals_perround_round_3_ctrl_f1,totals_perround_round_3_ctrl_f2,significant_strikes_perround_round_1_fighter_f1,significant_strikes_perround_round_1_fighter_f2,significant_strikes_perround_round_1_fighter_f1_url,significant_strikes_perround_round_1_fighter_f2_url,significant_strikes_perround_round_1_sig_str_f1,significant_strikes_perround_round_1_sig_str_f2,significant_strikes_perround_round_1_head_f1,significant_strikes_perround_round_1_head_f2,significant_strikes_perround_round_1_body_f1,significant_strikes_perround_round_1_body_f2,significant_strikes_perround_round_1_leg_f1,significant_strikes_perround_round_1_leg_f2,significant_strikes_perround_round_1_distance_f1,significant_strikes_perround_round_1_distance_f2,significant_strikes_perround_round_1_clinch_f1,significant_strikes_perround_round_1_clinch_f2,significant_strikes_perround_round_1_ground_f1,significant_strikes_perround_round_1_ground_f2,significant_strikes_perround_round_2_fighter_f1,significant_strikes_perround_round_2_fighter_f2,significant_strikes_perround_round_2_fighter_f1_url,significant_strikes_perround_round_2_fighter_f2_url,significant_strikes_perround_round_2_sig_str_f1,significant_strikes_perround_round_2_sig_str_f2,significant_strikes_perround_round_2_head_f1,significant_strikes_perround_round_2_head_f2,significant_strikes_perround_round_2_body_f1,significant_strikes_perround_round_2_body_f2,significant_strikes_perround_round_2_leg_f1,significant_strikes_perround_round_2_leg_f2,significant_strikes_perround_round_2_distance_f1,significant_strikes_perround_round_2_distance_f2,significant_strikes_perround_round_2_clinch_f1,significant_strikes_perround_round_2_clinch_f2,significant_strikes_perround_round_2_ground_f1,significant_strikes_perround_round_2_ground_f2,significant_strikes_perround_round_3_fighter_f1,significant_strikes_perround_round_3_fighter_f2,significant_strikes_perround_round_3_fighter_f1_url,significant_strikes_perround_round_3_fighter_f2_url,significant_strikes_perround_round_3_sig_str_f1,significant_strikes_perround_round_3_sig_str_f2,significant_strikes_perround_round_3_head_f1,significant_strikes_perround_round_3_head_f2,significant_strikes_perround_round_3_body_f1,significant_strikes_perround_round_3_body_f2,significant_strikes_perround_round_3_leg_f1,significant_strikes_perround_round_3_leg_f2,significant_strikes_perround_round_3_distance_f1,significant_strikes_perround_round_3_distance_f2,significant_strikes_perround_round_3_clinch_f1,significant_strikes_perround_round_3_clinch_f2,significant_strikes_perround_round_3_ground_f1,significant_strikes_perround_round_3_ground_f2,totals_perround_round_4_fighter_f1,totals_perround_round_4_fighter_f2,totals_perround_round_4_fighter_f1_url,totals_perround_round_4_fighter_f2_url,totals_perround_round_4_kd_f1,totals_perround_round_4_kd_f2,totals_perround_round_4_sig_str_f1,totals_perround_round_4_sig_str_f2,totals_perround_round_4_total_str_f1,totals_perround_round_4_total_str_f2,totals_perround_round_4_td_f1,totals_perround_round_4_td_f2,totals_perround_round_4_sub_att_f1,totals_perround_round_4_sub_att_f2,totals_perround_round_4_rev_f1,totals_perround_round_4_rev_f2,totals_perround_round_4_ctrl_f1,totals_perround_round_4_ctrl_f2,significant_strikes_perround_round_4_fighter_f1,significant_strikes_perround_round_4_fighter_f2,significant_strikes_perround_round_4_fighter_f1_url,significant_strikes_perround_round_4_fighter_f2_url,significant_strikes_perround_round_4_sig_str_f1,significant_strikes_perround_round_4_sig_str_f2,significant_strikes_perround_round_4_head_f1,significant_strikes_perround_round_4_head_f2,significant_strikes_perround_round_4_body_f1,significant_strikes_perround_round_4_body_f2,significant_strikes_perround_round_4_leg_f1,significant_strikes_perround_round_4_leg_f2,significant_strikes_perround_round_4_distance_f1,significant_strikes_perround_round_4_distance_f2,significant_strikes_perround_round_4_clinch_f1,significant_strikes_perround_round_4_clinch_f2,significant_strikes_perround_round_4_ground_f1,significant_strikes_perround_round_4_ground_f2,totals_perround_round_5_fighter_f1,totals_perround_round_5_fighter_f2,totals_perround_round_5_fighter_f1_url,totals_perround_round_5_fighter_f2_url,totals_perround_round_5_kd_f1,totals_perround_round_5_kd_f2,totals_perround_round_5_sig_str_f1,totals_perround_round_5_sig_str_f2,totals_perround_round_5_total_str_f1,totals_perround_round_5_total_str_f2,totals_perround_round_5_td_f1,totals_perround_round_5_td_f2,totals_perround_round_5_sub_att_f1,totals_perround_round_5_sub_att_f2,totals_perround_round_5_rev_f1,totals_perround_round_5_rev_f2,totals_perround_round_5_ctrl_f1,totals_perround_round_5_ctrl_f2,significant_strikes_perround_round_5_fighter_f1,significant_strikes_perround_round_5_fighter_f2,significant_strikes_perround_round_5_fighter_f1_url,significant_strikes_perround_round_5_fighter_f2_url,significant_strikes_perround_round_5_sig_str_f1,significant_strikes_perround_round_5_sig_str_f2,significant_strikes_perround_round_5_head_f1,significant_strikes_perround_round_5_head_f2,significant_strikes_perround_round_5_body_f1,significant_strikes_perround_round_5_body_f2,significant_strikes_perround_round_5_leg_f1,significant_strikes_perround_round_5_leg_f2,significant_strikes_perround_round_5_distance_f1,significant_strikes_perround_round_5_distance_f2,significant_strikes_perround_round_5_clinch_f1,significant_strikes_perround_round_5_clinch_f2,significant_strikes_perround_round_5_ground_f1,significant_strikes_perround_round_5_ground_f2
0,http://ufcstats.com/fight-details/012c307c9d446c4d,UFC Fight Night: Fiziev vs. Torres,http://ufcstats.com/event-details/31e1ea6fe6b682f8,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,W,L,"""Bullet""","""Demolidor""",Middleweight Bout,0,0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Herb Dean,NaN,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,0,1,85%,53%,53 of 71,37 of 56,---,---,0,0,1,0,0:42,3:24,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,0.0,0.0,57%,35%,20 of 35,6 of 17,---,---,0.0,0.0,0.0,0.0,0:00,0:00,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,0.0,0.0,60%,37%,39 of 59,18 of 40,---,0%,0.0,0.0,0.0,0.0,0:11,0:40,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,85%,53%,3 of 4,14 of 28,0 of 0,2 of 2,3 of 3,0 of 0,4 of 4,1 of 3,0 of 0,0 of 0,2 of 3,15 of 27,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,57%,35%,4 of 16,3 of 11,7 of 9,2 of 5,9 of 10,1 of 1,19 of 33,6 of 17,1 of 2,0 of 0,0 of 0,0 of 0,Shara Magomedov,Michel Pereira,http://ufcstats.com/fighter-details/06734ca9d88dec3a,http://ufcstats.com/fighter-details/595db60957de51d3,60%,37%,9 of 19,4 of 16,11 of 15,5 of 9,6 of 9,4 of 10,21 of 38,12 of 34,4 of 4,1 of 1,1 of 1,0 of 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,http://ufcstats.com/fight-details/809814f03ff3140c,UFC Fight Night: Fiziev vs. Torres,http://ufcstats.com/event-details/31e1ea6fe6b682f8,Nazim Sadykhov,Matheus Camilo,http://ufcstats.com/fighter-details/ff62013d2fce6d13,http://ufcstats.com/fighter-details/72f890c5d421e705,L,W,"""Black Wolf""","""Jaguar""",Lightweight Bout,0,0,KO/TKO,1,1:31,3 Rnd (5-5-5),Rich Mitchell,NaN,Nazim Sadykhov,Matheus Camilo,http://ufcstats.com/fighter-details/ff62013d2fce6d13,http://ufcstats.com/fighter-details/72f890c5d421e705,0,1,0%,40%,0 of 16,4 of 10,---,---,0,0,0,0,0:00,0:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nazim Sadykhov,Matheus Camilo,http://ufcstats.com/fighter-details/ff62013d2fce6d13,http://ufcstats.com/fighter-details/72f890c5d421e705,0%,40%,0 of 10,3 of 8,0 of 1,0 of 0,0 of 5,1 of 2,0 of 16,2 of 6,0 of 0,0 of 0,0 of 0,2 of 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,http://ufcstats.com/fight-details/81cde317c156723b,UFC Fight Night: Fiziev vs. Torres,http://ufcstats.com/event-details/31e1ea6fe6b682f8,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,W,L,"""Zulfikar""","""InnerG""",Flyweight Bout,0,1,Submission,3,3:33,3 Rnd (5-5-5),Herb Dean,NaN,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,0,0,47%,36%,23 of 36,8 of 16,75%,---,0,0,0,0,3:19,0:00,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,0.0,0.0,51%,50%,26 of 40,19 of 34,50%,---,0.0,0.0,0.0,0.0,2:26,0:00,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,0.0,0.0,85%,50%,24 of 26,5 of 7,100%,---,1.0,1.0,0.0,0.0,3:03,0:00,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,47%,36%,6 of 13,0 of 2,0 of 2,4 of 6,2 of 2,0 of 3,5 of 11,2 of 9,0 of 0,2 of 2,3 of 6,0 of 0,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,51%,50%,5 of 16,4 of 15,6 of 7,4 of 7,3 of 4,7 of 8,10 of 22,14 of 28,1 of 1,1 of 2,3 of 4,0 of 0,Asu Almabayev,Charles Johnson,http://ufcstats.com/fighter-details/8d3273573b85be09,http://ufcstats.com/fighter-details/814e5233e2acf2ee,85%,50%,4 of 5,1 of 2,1 of 1,0 of 1,1 of 1,1 of 1,3 of 4,2 of 4,0 of 0,0 of 0,3 of 3,0 of 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,http://ufcstats.com/fight-details/d83294b031502177,UFC Fight Night: Fiziev vs. Torres,http://ufcstats.com/event-details/31e1ea6fe6b682f8,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,W,L,NaN,"""The Hulk""",Middleweight Bout,0,0,Decision - Unanimous,3,5:00,3 Rnd (5-5-5),Marc Goddard,NaN,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,0,0,51%,60%,39 of 57,7 of 12,66%,---,0,0,0,0,2:44,0:00,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,0.0,0.0,51%,38%,24 of 45,11 of 28,100%,0%,0.0,0.0,0.0,0.0,2:30,0:07,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,0.0,0.0,40%,15%,51 of 77,5 of 21,100%,---,1.0,0.0,0.0,0.0,3:39,0:00,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,51%,60%,9 of 23,3 of 7,2 of 2,1 of 1,4 of 4,2 of 2,14 of 27,6 of 10,0 of 1,0 of 0,1 of 1,0 of 0,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,51%,38%,13 of 31,8 of 24,5 of 6,1 of 1,2 of 2,1 of 1,17 of 35,10 of 26,0 of 0,0 of 0,3 of 4,0 of 0,Ikram Aliskerov,Brunno Ferreira,http://ufcstats.com/fighter-details/b07aed698fba8624,http://ufcstats.com/fighter-details/1e719d4b676dc19a,40%,15%,10 of 26,2 of 17,2 of 4,1 of 2,0 of 0,0 of 0,5 of 22,3 of 19,0 of 0,0 of 0,7 of 8,0 of 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,http://ufcstats.com/fight-details/35985895d4ef321e,UFC Fight Night: Fiziev vs. Torres,http://ufcstats.com/event-details/31e1ea6fe6b682f8,Abus Magomedov,Michal Oleksiejczuk,http://ufcstats.com/fighter-details/36b8f265bcd1b7a4,http://ufcstats.com/fighter-details/0d65c432720accb9,W,L,NaN,"""Hussar""",Middleweight Bout,0,0,Submission,1,3:25,3 Rnd (5-5-5),Jim Perdios,NaN,Abus Magomedov,Michal Oleksiejczuk,http://ufcstats.com/fighter-details/36b8f265bcd1b7a4,http://ufcstats.com/fighter-details/0d65c432720accb9,1,0,37%,26%,10 of 27,5 of 19,---,---,1,0,0,0,0:36,0:03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abus Magomedov,Michal Oleksiejczuk,http://ufcstats.com/fighter-details/36b8f265bcd1b7a4,http://ufcstats.com/fighter-details/0d65c432720accb9,37%,26%,5 of 20,1 of 12,4 of 5,2 of 4,1 of 2,2 of 3,9 of 25,5 of 19,1 of 1,0 of 0,0 of 1,0 of 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fight_stats.columns = fight_stats.columns.str.replace("totals_perround_", "")
fight_stats.columns = fight_stats.columns.str.replace("round_", "r")  
fight_stats.columns = fight_stats.columns.str.replace("significant_strikes_perr", "sg_strk_")  
fight_stats.columns = fight_stats.columns.str.replace("is_title_bout", "title") 
fight_stats.columns = fight_stats.columns.str.replace("time_format", "set_rounds")
fight_stats.columns = fight_stats.columns.str.replace("time", "last_rnd_time")

fight_stats = fight_stats.drop(columns=[
    "event_url",
    "perf_bonus",
    "details", "referee",
    "fight_url",
    "nickname_f1","nickname_f2",
    "fighter_f1_url","fighter_f2_url",
     "r1_fighter_f1","r1_fighter_f2", "r1_fighter_f1_url","r1_fighter_f2_url",
    "r2_fighter_f1","r2_fighter_f2", "r2_fighter_f1_url","r2_fighter_f2_url",
    "r3_fighter_f1","r3_fighter_f2", "r3_fighter_f1_url","r3_fighter_f2_url",
    "r4_fighter_f1","r4_fighter_f2", "r4_fighter_f1_url","r4_fighter_f2_url",
    "r5_fighter_f1","r5_fighter_f2", "r5_fighter_f1_url","r5_fighter_f2_url",
    "sg_strk_r1_fighter_f1", "sg_strk_r1_fighter_f2", "sg_strk_r1_fighter_f1_url", "sg_strk_r1_fighter_f2_url",
    "sg_strk_r2_fighter_f1", "sg_strk_r2_fighter_f2", "sg_strk_r2_fighter_f1_url", "sg_strk_r2_fighter_f2_url",
    "sg_strk_r3_fighter_f1", "sg_strk_r3_fighter_f2", "sg_strk_r3_fighter_f1_url", "sg_strk_r3_fighter_f2_url",
    "sg_strk_r4_fighter_f1", "sg_strk_r4_fighter_f2", "sg_strk_r4_fighter_f1_url", "sg_strk_r4_fighter_f2_url",
    "sg_strk_r5_fighter_f1", "sg_strk_r5_fighter_f2", "sg_strk_r5_fighter_f1_url", "sg_strk_r5_fighter_f2_url"
                             ])


fight_stats["outcome_f1"] = fight_stats["outcome_f1"].map({"W": 1, "L": 0, "NC": 2, "D":3}).astype("Int64")
fight_stats["outcome_f2"] = fight_stats["outcome_f2"].map({"W": 1, "L": 0, "NC": 2, "D":3}).astype("Int64")
fight_stats["set_rounds"] = fight_stats["set_rounds"].astype(str).str.extract(r"(\d+)")
fight_stats['last_rnd_time'] = pd.to_timedelta( fight_stats['last_rnd_time'].apply(lambda x: f"00:{x}" if len(x.split(':')) == 2 else x)).dt.total_seconds().astype(int)

fight_stats["round"] = fight_stats["round"].astype(int)

percent_columns = [
    col for col in fight_stats.select_dtypes(include=['object', 'category']).columns
    if fight_stats[col].astype(str).str.contains('%').any()
]
for col in percent_columns:
    cleaned_series = fight_stats[col].astype(str).str.rstrip('%').str.strip()
    fight_stats[col] = pd.to_numeric(cleaned_series, errors='coerce') / 100  

of_columns = [
    col for col in fight_stats.select_dtypes(include=['object', 'category']).columns
    if fight_stats[col].astype(str).str.contains(' of ').any()
]
for col in of_columns:
    split_df = fight_stats[col].astype(str).str.split(' of ', expand=True)
    numerator = pd.to_numeric(split_df[0], errors='coerce')
    denominator = pd.to_numeric(split_df[1], errors='coerce')
    fight_stats[col] = numerator / denominator.replace(0, np.nan)

time_columns = [
    col for col in fight_stats.select_dtypes(include=['object', 'category']).columns
    if fight_stats[col].astype(str).str.contains(':').any() and "event" not in col.lower()
]

for col in time_columns:
    time_parts = fight_stats[col].astype(str).str.split(':')
    fight_stats[col] = time_parts.apply(
        lambda x: int(x[0]) * 60 + int(x[1]) if isinstance(x, list) and len(x) == 2 and x[0].isdigit() and x[1].isdigit() else None
    )




fight_stats["tot_fight_time"] = fight_stats["last_rnd_time"] + (fight_stats["round"] - 1) * 300

fight_stats.insert(9, "tot_fight_time", fight_stats.pop("tot_fight_time"))


print(len(fight_stats.columns))
print((fight_stats.columns.dtype))
print((fight_stats.columns))
#fight_stats_null = fight_stats[fight_stats["outcome_f1"].isnull()]
fight_stats

C:\Users\brand\AppData\Local\Temp\ipykernel_11112\3515719498.py:45: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col for col in fight_stats.select_dtypes(include=['object', 'category']).columns
C:\Users\brand\AppData\Local\Temp\ipykernel_11112\3515719498.py:53: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col for col in fight_stats.select_dtypes(include=['object', 'category']).columns

152
str
Index(['event_name', 'fighter_f1', 'fighter_f2', 'outcome_f1', 'outcome_f2',
       'bout_type', 'title', 'method', 'round', 'tot_fight_time',
       ...
       'sg_strk_r5_body_f1', 'sg_strk_r5_body_f2', 'sg_strk_r5_leg_f1',
       'sg_strk_r5_leg_f2', 'sg_strk_r5_distance_f1', 'sg_strk_r5_distance_f2',
       'sg_strk_r5_clinch_f1', 'sg_strk_r5_clinch_f2', 'sg_strk_r5_grf1',
       'sg_strk_r5_grf2'],
      dtype='str', length=152)

C:\Users\brand\AppData\Local\Temp\ipykernel_11112\3515719498.py:64: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  col for col in fight_stats.select_dtypes(include=['object', 'category']).columns
C:\Users\brand\AppData\Local\Temp\ipykernel_11112\3515719498.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  fight_stats["tot_fight_time"] = fight_stats["last_rnd_time"] + (fight_stats["round"] - 1) * 300
C:\Users\brand\AppData\Local\Temp\ipykernel_11112\3515719498.py:79: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  fight_stats.insert(9, "tot_fight_time", fight_stats.pop("tot_fight_time"))

,event_name,fighter_f1,fighter_f2,outcome_f1,outcome_f2,bout_type,title,method,round,tot_fight_time,last_rnd_time,set_rounds,r1_kd_f1,r1_kd_f2,r1_sig_str_f1,r1_sig_str_f2,r1_total_str_f1,r1_total_str_f2,r1_td_f1,r1_td_f2,r1_sub_att_f1,r1_sub_att_f2,r1_rev_f1,r1_rev_f2,r1_ctrl_f1,r1_ctrl_f2,r2_kd_f1,r2_kd_f2,r2_sig_str_f1,r2_sig_str_f2,r2_total_str_f1,r2_total_str_f2,r2_td_f1,r2_td_f2,r2_sub_att_f1,r2_sub_att_f2,r2_rev_f1,r2_rev_f2,r2_ctrl_f1,r2_ctrl_f2,r3_kd_f1,r3_kd_f2,r3_sig_str_f1,r3_sig_str_f2,r3_total_str_f1,r3_total_str_f2,r3_td_f1,r3_td_f2,r3_sub_att_f1,r3_sub_att_f2,r3_rev_f1,r3_rev_f2,r3_ctrl_f1,r3_ctrl_f2,sg_strk_r1_sig_str_f1,sg_strk_r1_sig_str_f2,sg_strk_r1_head_f1,sg_strk_r1_head_f2,sg_strk_r1_body_f1,sg_strk_r1_body_f2,sg_strk_r1_leg_f1,sg_strk_r1_leg_f2,sg_strk_r1_distance_f1,sg_strk_r1_distance_f2,sg_strk_r1_clinch_f1,sg_strk_r1_clinch_f2,sg_strk_r1_grf1,sg_strk_r1_grf2,sg_strk_r2_sig_str_f1,sg_strk_r2_sig_str_f2,sg_strk_r2_head_f1,sg_strk_r2_head_f2,sg_strk_r2_body_f1,sg_strk_r2_body_f2,sg_strk_r2_leg_f1,sg_strk_r2_leg_f2,sg_strk_r2_distance_f1,sg_strk_r2_distance_f2,sg_strk_r2_clinch_f1,sg_strk_r2_clinch_f2,sg_strk_r2_grf1,sg_strk_r2_grf2,sg_strk_r3_sig_str_f1,sg_strk_r3_sig_str_f2,sg_strk_r3_head_f1,sg_strk_r3_head_f2,sg_strk_r3_body_f1,sg_strk_r3_body_f2,sg_strk_r3_leg_f1,sg_strk_r3_leg_f2,sg_strk_r3_distance_f1,sg_strk_r3_distance_f2,sg_strk_r3_clinch_f1,sg_strk_r3_clinch_f2,sg_strk_r3_grf1,sg_strk_r3_grf2,r4_kd_f1,r4_kd_f2,r4_sig_str_f1,r4_sig_str_f2,r4_total_str_f1,r4_total_str_f2,r4_td_f1,r4_td_f2,r4_sub_att_f1,r4_sub_att_f2,r4_rev_f1,r4_rev_f2,r4_ctrl_f1,r4_ctrl_f2,sg_strk_r4_sig_str_f1,sg_strk_r4_sig_str_f2,sg_strk_r4_head_f1,sg_strk_r4_head_f2,sg_strk_r4_body_f1,sg_strk_r4_body_f2,sg_strk_r4_leg_f1,sg_strk_r4_leg_f2,sg_strk_r4_distance_f1,sg_strk_r4_distance_f2,sg_strk_r4_clinch_f1,sg_strk_r4_clinch_f2,sg_strk_r4_grf1,sg_strk_r4_grf2,r5_kd_f1,r5_kd_f2,r5_sig_str_f1,r5_sig_str_f2,r5_total_str_f1,r5_total_str_f2,r5_td_f1,r5_td_f2,r5_sub_att_f1,r5_sub_att_f2,r5_rev_f1,r5_rev_f2,r5_ctrl_f1,r5_ctrl_f2,sg_strk_r5_sig_str_f1,sg_strk_r5_sig_str_f2,sg_strk_r5_head_f1,sg_strk_r5_head_f2,sg_strk_r5_body_f1,sg_strk_r5_body_f2,sg_strk_r5_leg_f1,sg_strk_r5_leg_f2,sg_strk_r5_distance_f1,sg_strk_r5_distance_f2,sg_strk_r5_clinch_f1,sg_strk_r5_clinch_f2,sg_strk_r5_grf1,sg_strk_r5_grf2
0,UFC Fight Night: Fiziev vs. Torres,Shara Magomedov,Michel Pereira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,300,3,0,1,0.85,0.53,0.746479,0.660714,NaN,NaN,0,0,1,0,42,204,0.0,0.0,0.57,0.35,0.571429,0.352941,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.60,0.37,0.661017,0.450000,NaN,0.0,0.0,0.0,0.0,0.0,11.0,40.0,0.85,0.53,0.750000,0.500000,NaN,1.000000,1.000000,NaN,1.000000,0.333333,NaN,NaN,0.666667,0.555556,0.57,0.35,0.250000,0.272727,0.777778,0.400000,0.900000,1.000000,0.575758,0.352941,0.500000,NaN,NaN,NaN,0.60,0.37,0.473684,0.250000,0.733333,0.555556,0.666667,0.40,0.552632,0.352941,1.0,1.000000,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UFC Fight Night: Fiziev vs. Torres,Nazim Sadykhov,Matheus Camilo,0,1,Lightweight Bout,0,KO/TKO,1,91,91,3,0,1,0.00,0.40,0.000000,0.400000,NaN,NaN,0,0,0,0,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.40,0.000000,0.375000,0.000000,NaN,0.000000,0.500000,0.000000,0.333333,NaN,NaN,NaN,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UFC Fight Night: Fiziev vs. Torres,Asu Almabayev,Charles Johnson,1,0,Flyweight Bout,0,Submission,3,813,213,3,0,0,0.47,0.36,0.638889,0.500000,0.75,NaN,0,0,0,0,199,0,0.0,0.0,0.51,0.50,0.650000,0.558824,0.5,NaN,0.0,0.0,0.0,0.0,146.0,0.0,0.0,0.0,0.85,0.50,0.923077,0.714286,1.00,NaN,1.0,1.0,0.0,0.0,183.0,0.0,0.47,0.36,0.461538,0.000000,0.000000,0.666667,1.000000,0.000000,0.454545,0.222222,NaN,1.000000,0.500000,NaN,0.51,0.50,0.312500,0.266667,0.857143,0.571429,0.750000,0.875000,0.454545,0.500000,1.000000,0.5,0.750000,NaN,0.85,0.50,0.800000,0.500000,1.000000,0.000000,1.000000,1.00,0.750000,0.500000,NaN,NaN,1.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UFC Fight Night: Fiziev vs. Torres,Ikram Aliskerov,Brunno Ferreira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,300,3,0,0,0.51,0.60,0.684211,0.583333,0.66,NaN,0,0,0,0,164,0,0.0,0.0,0.51,0.38,0.533333,0.392857,1.0,0.00,0.0,0.0,0.0,0.0,150.0,7.0,0.0,0.0,0.40,0.15,0.662338,0.238095,1.00,NaN,1.0,0.0,0.0,0.0,219.0,0.0,0.51,0.60,0.391304,0.428571,1.000000,1.000000,1.000000,1.000000,0.518519,0.600000,0.00,NaN,1.000000,NaN,0.51,0.38,0.419355,0.333333,0.833333,1.000000,1.000000,1.000000,0.485714,0.384615,NaN,NaN,0.750000,NaN,0.40,0.15,0.384615,0.117647,0.500000,0.500000,NaN,NaN,0.227273,0.157895,NaN,NaN,0.875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UFC Fight Night: Fiziev vs. Torres,Abus Magomedov,Michal Oleksiejczuk,1,0,Middleweight Bout,0,Submission,1,205,205,3,1,0,0.37,0.26,0.370370,0.263158,NaN,NaN,1,0,0,0,36,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.37,0.26,0.250000,0.083333,0.800000,0.500000,0.500000,0.666667,0.360000,0.263158,1.00,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,UFC Fight Night: Cannonier vs. Strickland,Bryan Battle,Rinat Fakhretdinov,0,1,Welterweight Bout,0,Decision - Unanimous,3,900,300,3,0,0,0.33,0.63,0.600000,0.711538,NaN,0.66,0,0,0,0,0,281,0.0,0.0,0.20,0.66,0.666667,0.714286,NaN,0.66,0.0,0.0,0.0,0.0,0.0,289.0,0.0,1.0,0.12,0.60,0.526316,0.636364,0.00,1.0,0.0,0.0,0.0,0.0,0.0,281.0,0.33,0.63,0.500000,0.592593,0.000000,1.000000,NaN,1.000000,0.333333,0.800000,NaN,NaN,NaN,0.600000,0.20,0.66,0.000000,0.642857,1.000000,1.000000,NaN,NaN,0.200000,0.666667,NaN,NaN,NaN,0.666667,0.12,0.60,0.000000,0.619048,0.000000,0.000000,1.000000,1.00,0.125000,0.666667,NaN,0.666667,NaN,0.588235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1830,UFC Fight Night: Cannonier vs. Strickland,David Dvorak,Manel Kape,0,1,Flyweight Bout,0,Decision - Unanimous,3,900,300,3,0,0,0.40,0.22,0.615385,0.388889,1.00,NaN,0,2,0,1,119,17,0.0,1.0,0.42,0.58,0.520833,0.558824,1.0,NaN,0.0,0.0,0.0,0.0,29.0,40.0,0.0,0.0,0.28,0.40,0.291667,0.440000,0.00,NaN,0.0,0.0,0.0,0.0,14.0,0.0,0.40,0.22,0.222222,0.285714,0.000000,0.000000,1.000000,0.000000,0.357143,0.222222,NaN,NaN,1.000000,NaN,0.42,0.58,0.315789,0.488889,0.625000,0.875000,0.500000,0.500000,0.406250,0.545455,1.000000,1.0,NaN,0.600000,0.28,0.40,0.225000,0.272727,0.500000,0.555556,0.750000,1.00,0.288889,0.391304,0.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1831,UFC Fight Night: Cannonier vs. Strickland,Sergey Morozov,Journey Newson,1,0,Bantamweight Bout,0,Decision - Unanimous,3,900,300,3,0,0,0.27,0.21,0.340426,0.229167,1.00,0.00,0,0,0,0,84,0,0.0,0.0,0.28,0.25,0.428571,0.358974,0.4,NaN,0.0,0.0,0.0,0.0,141.0,0.0,0.0,0.0,0.29,0.29,0.571429,0.489796,0.33,0.0,0.0,0.0,0.0,0.0,194.0,0.0,0.27,0.21,0.117647,0.150000,0.666667,0.500000,1.000000,1.000000,0.216216,0.217391,0.75,0.000000,0.500000,NaN,0.28,0.25,0.080000,0.000000,0.714286,0.600000,0.666667,0.555556,0.161290,0.250000,0.666667,NaN,1.000000,NaN,0.29,0.29,0.058824,0.200000,0.500000,0.333333,1.000000,0.75,0.150000,0.269231,1.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1832,UFC Fight Night: Dolidze vs. Hernandez,Uros Medic,Gilbert Urbina,1,0,Welterweight Bout,0,KO/TKO,1,63,63,3,1,1,0.55,0.50,0.600000,0.500000,NaN,NaN,0,0,0,0,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.55,0.50,0.500000,0.428571,1.000000,0.500000,NaN,1.000000,0.428571,0.500000,1.00,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1833,UFC Fight Night: Fiziev vs. Torres,Rafael Fiziev,Manuel Torres,1,0,Lightweight Bout,0,KO/TKO,2,315,15,5,0,0,0.60,0.41,0.620690,0.454545,1.00,NaN,0,0,0,0,36,6,1.0,0.0,0.71,1.00,0.714286,1.000000,NaN,NaN,0.0,0.0,0.0,0.0,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.60,0.41,0.500000,0.340909,0.333333,0.800000,0.714286,1.000000,0.583333,0.416667,NaN,0.333333,1.000000,NaN,0.71,1.00,0.692308,1.000000,1.000000,NaN,NaN,NaN,0.666667,NaN,0.600000,1.0,0.833333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
fighters = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\data_stats_fighters.csv")
fighters

,fighter,Height,Weight,Reach,STANCE,DOB,SLpM,Str. Acc.,SApM,Str. Def,TD Avg.,TD Acc.,TD Def.,Sub. Avg.
0,Rafael Fiziev,"5' 8""",155 lbs.,"71""",Switch,03/05/1993,4.71,52%,4.81,50%,1.00,71%,90%,0.0
1,Shara Magomedov,"6' 2""",185 lbs.,"73""",Orthodox,05/16/1994,5.55,62%,3.62,45%,0.00,0%,73%,0.0
2,Matheus Camilo,"5' 10""",155 lbs.,"69""",Orthodox,01/02/2001,2.22,43%,3.05,66%,4.16,53%,0%,0.6
3,Asu Almabayev,"5' 4""",125 lbs.,"65""",Orthodox,01/25/1994,2.28,51%,1.94,53%,4.74,45%,44%,1.4
4,Ikram Aliskerov,"6' 0""",185 lbs.,"76""",Southpaw,12/07/1992,5.56,60%,4.01,45%,3.82,68%,100%,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,Mauricio Rua,"6' 1""",205 lbs.,"76""",Orthodox,11/25/1981,3.57,50%,2.79,54%,2.01,48%,49%,0.7
939,Mounir Lazzez,"6' 1""",170 lbs.,"76""",Orthodox,11/16/1987,7.49,55%,5.42,53%,1.80,57%,71%,0.0
940,Shamil Abdurakhimov,"6' 3""",235 lbs.,"76""",Orthodox,09/02/1981,2.41,44%,3.02,55%,1.01,23%,45%,0.1
941,Cheyanne Vlismas,"5' 3""",115 lbs.,"63""",Switch,06/25/1995,4.93,50%,2.57,64%,0.25,33%,66%,0.2
942,Saidyokub Kakhramonov,"5' 8""",135 lbs.,"69""",Orthodox,11/14/1995,2.05,51%,0.88,58%,6.63,48%,83%,1.9

In [ ]:
events = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\data_stats_fighters.csv")
events

In [ ]:
fight_stats.to_csv(r"C:\Git projects\ufc_ml\ufc_data\fight_details_clean.csv", index=False)