In [28]:
import pandas as pd

fighters = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\slv\data_stats_fighters.csv")
display(fighters)
events = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\lists\list_fights.csv")
display(events)
fight_stats = pd.read_csv(r"C:\Git projects\ufc_ml\ufc_data\slv\fight_details_clean.csv")
display(fight_stats)

                   fighter  Height  Weight  Reach    STANCE         DOB
0            Rafael Fiziev      68   155.0     71    Switch  03/05/1993
1          Shara Magomedov      74   185.0     73  Orthodox  05/16/1994
2           Matheus Camilo      70   155.0     69  Orthodox  01/02/2001
3            Asu Almabayev      64   125.0     65  Orthodox  01/25/1994
4          Ikram Aliskerov      72   185.0     76  Southpaw  12/07/1992
..                     ...     ...     ...    ...       ...         ...
938           Mauricio Rua      73   205.0     76  Orthodox  11/25/1981
939          Mounir Lazzez      73   170.0     76  Orthodox  11/16/1987
940    Shamil Abdurakhimov      75   235.0     76  Orthodox  09/02/1981
941       Cheyanne Vlismas      63   115.0     63    Switch  06/25/1995
942  Saidyokub Kakhramonov      68   135.0     69  Orthodox  11/14/1995

[943 rows x 6 columns]

,event_name,event_date,fight_url
0,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/c13dc0cccef2...
1,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/012c307c9d44...
2,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/809814f03ff3...
3,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/81cde317c156...
4,UFC Fight Night: Fiziev vs. Torres,06/27/2026,http://ufcstats.com/fight-details/d83294b03150...
...,...,...,...
1829,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/ed6203e849a2...
1830,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/efc64d8aae56...
1831,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/8f00da6ea818...
1832,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/f87a7812733f...
1833,UFC Fight Night: Cannonier vs. Strickland,12/17/2022,http://ufcstats.com/fight-details/ccb7e2851319...

,event_name,fighter_f1,fighter_f2,outcome_f1,outcome_f2,bout_type,title,method,round,tot_fight_time,...,sg_strk_r5_body_f1,sg_strk_r5_body_f2,sg_strk_r5_leg_f1,sg_strk_r5_leg_f2,sg_strk_r5_distance_f1,sg_strk_r5_distance_f2,sg_strk_r5_clinch_f1,sg_strk_r5_clinch_f2,sg_strk_r5_grf1,sg_strk_r5_grf2
0,UFC Fight Night: Fiziev vs. Torres,Shara Magomedov,Michel Pereira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UFC Fight Night: Fiziev vs. Torres,Nazim Sadykhov,Matheus Camilo,0,1,Lightweight Bout,0,KO/TKO,1,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UFC Fight Night: Fiziev vs. Torres,Asu Almabayev,Charles Johnson,1,0,Flyweight Bout,0,Submission,3,813,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,UFC Fight Night: Fiziev vs. Torres,Ikram Aliskerov,Brunno Ferreira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,UFC Fight Night: Fiziev vs. Torres,Abus Magomedov,Michal Oleksiejczuk,1,0,Middleweight Bout,0,Submission,1,205,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1829,UFC Fight Night: Cannonier vs. Strickland,Bryan Battle,Rinat Fakhretdinov,0,1,Welterweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1830,UFC Fight Night: Cannonier vs. Strickland,David Dvorak,Manel Kape,0,1,Flyweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1831,UFC Fight Night: Cannonier vs. Strickland,Sergey Morozov,Journey Newson,1,0,Bantamweight Bout,0,Decision - Unanimous,3,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1832,UFC Fight Night: Dolidze vs. Hernandez,Uros Medic,Gilbert Urbina,1,0,Welterweight Bout,0,KO/TKO,1,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1833,UFC Fight Night: Fiziev vs. Torres,Rafael Fiziev,Manuel Torres,1,0,Lightweight Bout,0,KO/TKO,2,315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fight_data = fight_stats.copy()
fight_data = fight_data.drop(columns=["event_date_x", "event_date_y", "event_date"], errors="ignore")

events_clean = events[["event_name", "event_date"]].drop_duplicates(subset=["event_name"], keep="first")
fight_data = fight_data.merge(events_clean, on="event_name", how="left")

fight_data = fight_data.merge(
    fighters.add_suffix("_f1"), 
    left_on="fighter_f1", 
    right_on="fighter_f1", 
    how="left"
)

fight_data = fight_data.merge(
    fighters.add_suffix("_f2"), 
    left_on="fighter_f2", 
    right_on="fighter_f2", 
    how="left"
)

fight_data["event_date"] = pd.to_datetime(fight_data["event_date"], errors="coerce")
fight_data["DOB_f1"] = pd.to_datetime(fight_data["DOB_f1"], errors="coerce")
fight_data["DOB_f2"] = pd.to_datetime(fight_data["DOB_f2"], errors="coerce")

fight_data["age_at_fight_f1"] = (fight_data["event_date"] - fight_data["DOB_f1"]).dt.days // 365
fight_data["age_at_fight_f2"] = (fight_data["event_date"] - fight_data["DOB_f2"]).dt.days // 365

fight_data = fight_data.drop(columns=["DOB_f1", "DOB_f2"], errors="ignore")

display(fight_data)

,event_name,fighter_f1,fighter_f2,outcome_f1,outcome_f2,bout_type,title,method,round,tot_fight_time,...,Reach_f1,STANCE_f1,DOB_f1,Height_f2,Weight_f2,Reach_f2,STANCE_f2,DOB_f2,age_at_fight_f1,age_at_fight_f2
0,UFC Fight Night: Fiziev vs. Torres,Shara Magomedov,Michel Pereira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,73,Orthodox,1994-05-16,73,185.0,73,Orthodox,1993-10-06,32,32
1,UFC Fight Night: Fiziev vs. Torres,Nazim Sadykhov,Matheus Camilo,0,1,Lightweight Bout,0,KO/TKO,1,91,...,69,Southpaw,1994-05-16,70,155.0,69,Orthodox,2001-01-02,32,25
2,UFC Fight Night: Fiziev vs. Torres,Asu Almabayev,Charles Johnson,1,0,Flyweight Bout,0,Submission,3,813,...,65,Orthodox,1994-01-25,69,125.0,70,Switch,1991-01-10,32,35
3,UFC Fight Night: Fiziev vs. Torres,Ikram Aliskerov,Brunno Ferreira,1,0,Middleweight Bout,0,Decision - Unanimous,3,900,...,76,Southpaw,1992-12-07,70,185.0,72,Orthodox,1992-11-04,33,33
4,UFC Fight Night: Fiziev vs. Torres,Abus Magomedov,Michal Oleksiejczuk,1,0,Middleweight Bout,0,Submission,1,205,...,78,Orthodox,1990-09-02,72,185.0,74,Southpaw,1995-02-22,35,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1842,UFC Fight Night: Cannonier vs. Strickland,Bryan Battle,Rinat Fakhretdinov,0,1,Welterweight Bout,0,Decision - Unanimous,3,900,...,77,Orthodox,1994-09-21,72,170.0,74,Orthodox,1991-09-28,28,31
1843,UFC Fight Night: Cannonier vs. Strickland,David Dvorak,Manel Kape,0,1,Flyweight Bout,0,Decision - Unanimous,3,900,...,68,Orthodox,1992-06-05,65,125.0,68,Southpaw,1993-11-14,30,29
1844,UFC Fight Night: Cannonier vs. Strickland,Sergey Morozov,Journey Newson,1,0,Bantamweight Bout,0,Decision - Unanimous,3,900,...,67,Orthodox,1989-06-14,65,135.0,67,Orthodox,1989-03-07,33,33
1845,UFC Fight Night: Dolidze vs. Hernandez,Uros Medic,Gilbert Urbina,1,0,Welterweight Bout,0,KO/TKO,1,63,...,71,Southpaw,1993-04-25,75,185.0,75,Orthodox,1996-04-05,32,29
1846,UFC Fight Night: Fiziev vs. Torres,Rafael Fiziev,Manuel Torres,1,0,Lightweight Bout,0,KO/TKO,2,315,...,71,Switch,1993-03-05,70,155.0,73,Switch,1995-03-25,33,31

In [30]:
fight_data.to_csv(r"C:\Git projects\ufc_ml\ufc_data\obt\fights_data.csv", index=False)